### ISSUE TITLE
Need extension for HtmlSubmitButton

### ISSUE THREAD

**Issue by ashjslaughter** [spelltwister/CodedUIFluentExtensions#1]
protected HtmlInputButton Submit
        {
            get
            {
                return this.Me.Find<HtmlInputButton>(HtmlControl.PropertyNames.Type, "submit",
                    PropertyExpressionOperator.EqualTo);
            }
        }

**Comment by spelltwister** [comment]
Added HmltSubmitButton.  Enjoy!
