### ISSUE TITLE
ISelectionModel with multiple Next Models

### ISSUE THREAD

**Issue by thePantz** [spelltwister/CodedUIFluentExtensions#12]
I have a combo box that changes the next model depending on which item is selected.

* Combo Box
  * Item 1 - Opens a window A when selected
  * Item 2 - Opens a window B when selected
  * Item 3 - Stays on the current window

I can't seem to accomplish with the given tools
`myComboBox.AsModel(windowA);` would make all items return window A

I have a similar issue with TabLists where each tab returns a different model.

This is an issue with ISelectionModel because it's list item can only have one Next Model.
Ideas on how to work around/Improve this?

**Comment by spelltwister** [comment]
Out of the box, the assumption is that each page model action returns the most like next model to work with.  In the case of multiple next models, you have a few options.

1.  Create methods which select the option from the drop down and create the appropriate model for return.  *not so great*  Option 2 is a better way to implement this.
2.  Do not use the SelectionPageModel and instead use SelectablePageModels.
3.  Return an object which represents all the possible next models and choose the one you want to make assertions again.  This can be helpful to ensure that the other actions are not performed.

Eg 2,
public class SomeControl : IPageModel, ISomeControlPageModel
{
    #region ComboBox Items
    ISelectablePageModel<TWindowA> ComboBoxOption1 {get;}
    ISelectablePageModel<TWindowB> ComboBoxOption2 {get;}
    ISelectablePageModel<ISomeControlPageModel> ComboBoxOption3{get;}
    #endregion

    // other model properties
}

[TestMethod]
public void GivenSomeControl_WhenSelectingOption1_ThenWindowAIsShownWithinHalfSecond()
{
    ISomeControlPageModel model;
    var windowA = model.ComboBoxOption1.SetSelected(true);

    Assert.IsTrue(windowA.IsRendered(500));
}

public class SomeControl : IPageModel, ISomeControlPageModel
{
    ISelectionPageModel<string, IMultiPageComboBoxResponse> Options {get;}
}

public interface IMultiPageComboBoxResponse : IPageModel
{
    IWindowAPageModel WindowA {get;}
    IWindowBPageModel WindowB {get;}
    ISomeControlPageModel Control {get;}
}

[TestMethod]
public void GivenSomeControl_WhenSelectingOption1_ThenWindowAIsShownWithinHalfSecond()
{
    ISomeControlPageModel model;
    var multiResponse = model.Options.Items.First().SetSelected(true);

    Assert.IsTrue(multiResponse.WindowA.IsRendered(500));
    Assert.IsFalse(multiResponse.WindowA.IsRendered(500));
    Assert.IsFalse(multiResponse.WindowA.IsRendered(500));
}

There are other ways to handle this, but I'd give one of these a try and see how it works out.

**Comment by thePantz** [comment]
I've used option 2 but found that it's only useful when dealing with static data, since you have to hard code each item in the collection.

I hadn't considered option 3, A collection that is dynamically populated would benefit from this greatly.
It's a bit awkward to implement though. IMultiPageComboBoxResponse isn't really a PageModel since it doesn't really represent any UI on the screen itself. 

 A concrete example would look something like this:

```
public class MyPage : PageModelBase<WinWindow>
{
     ISelectionPageModel<string, IMultiPageComboBoxResponse> Options { get { return Me.Find<WinComboBox>.AsModel(new MultiPageComboBox());
}



public class MultiPageComboBoxResponse : PageModelBase<UITestControl>, IMultiPageComboBoxResponse 
{
        IWindowAPageModel WindowA { get { return new WindowA(); } }
        ...

        protected override UITestControl Me
        {
            get { throw new NotImplementedException(); } //To Satisfy PageModelBase.... This object doesn't represent any UI itself
        }
}

[TestMethod]
public void GivenSomeControl_WhenSelectingOption1_ThenWindowAIsShownWithinHalfSecond()
{
    ISomeControlPageModel model;
    var multiResponse = model.Options.Items.First().SetSelected(true); //returns an IPageModel
    
    //All Options for an IPageModel are available... They will throw an exception since multiResponse doesn't represent UI
    multiResponse.IsActionable()
    multiResponse.IsRendered()
    multiResponse.CanFind()
    ...

    Assert.IsTrue(multiResponse.WindowA.IsRendered(500));
    Assert.IsFalse(multiResponse.WindowB.IsRendered(500));
    Assert.IsFalse(multiResponse.WindowC.IsRendered(500));
}


```


Not that you would ever want to use .IsActionable(), IsRendered(),.CanFind(), etc.  on multiResponse but options that are not applicable are displayed and will throw exceptions

**Comment by spelltwister** [comment]
Consider implementing the active window as me and it would be more natural and avoid the not implemented exception.

**Comment by spelltwister** [comment]
If the options in the drop down are dynamic and can open various windows, then a collection in the MultiResponse would be more appropriate.

    public interface IDynamicMultiPageComboBoxResponse : IPageModel
    {
        ICollection<IPageModel> PossibleNextModels {get;}
    }

    public class DynamicMultiPageComboBoxResponse : IPageModel // not based by a UI element
    {
         public DynamicMultiPageComboBoxResponse(IEnumerable<IPageModel> nextModels)
         {
             this.PossibleNextModels = nextModels.ToArray();
         }
         public ICollection<IPageModel> PossibleNextModels {get;}

        public bool IsRendered() { return this.GetActiveWindow.IsRendered(); } // do something like this for all the IPageModel stuff
    }

    public static class DynamicMultiPageComboBoxResponseExtensions
    {
        public static T GetModel<T>(this IDynamicMultiPageComboBoxResponse dynamicResponse)
        {
            return dynamicResponse.PossibleNextModels.OfType<T>().FirstOrDefault();
        }

        public static void AssertWindowRendered<T>(this IDynamicMultiPageComboBoxResponse dynamicResponse)
        {
            Assert.IsTrue(GetModel<T>(dynamicResponse).IsRendered()));
        }

        public static void AssertOnlyWindowRendered<T>(this IDynamicMultiPageComboBoxResponse dynamicResponse)
        {
            AssertWindowRendered<T>(dynamicResponse);
            Assert.IsTrue(dynamicResponse.PossibleNextModels.Where(IsRendered).Take(2).Count() == 1);
        }

        public static IPageModel GetActiveWindow(this IDynamicMultiPageComboBoxResponse dynamicResponse)
        {
            return dynamicResonse.PossibleNextModels.Where(IsRendered).Single();
        }

        public static T GetActiveWindowAs<T>(this IDynamicMultiPageComboBoxResponse dynamicResponse)
        {
            return dynamicResonse.PossibleNextModels.Where(IsRendered).OfType<T>().Single();
        }
    }

    [TestMethod]
    public void GivenSomeControl_WhenSelectingOption1_ThenWindowAIsShownWithinHalfSecond()
    {
        ISomeControlPageModel model;
        var multiResponse = model.Options.Items.First().SetSelected(true); //returns an IPageModel
        
        // Now these will work and represent the active window
        multiResponse.IsActionable()
        multiResponse.IsRendered()
        multiResponse.CanFind()
        ...

        Assert.IsTrue(multiResponse.WindowA.IsRendered(500));
        Assert.IsFalse(multiResponse.WindowB.IsRendered(500));
        Assert.IsFalse(multiResponse.WindowC.IsRendered(500));
    }

The code is just for example and you would have to decide what to do if there are multiple active windows or none.  The assumption was there would be one active next window.  You could extend it as needed to handle whatever scenario.
