### ISSUE TITLE
PageModeling namespace not available in version 0.8 of extensions from nuget

### ISSUE THREAD

**Issue by mkonkolowicz** [spelltwister/CodedUIFluentExtensions#4]
PageModeling namespace not available in version 0.8 of extensions from nuget. I updated my solution and noticed that all my objects from the page modeling space are not being recognized. I then investigated on github and noticed that you updated the structure. Can you ensure the page modeling space is included in the nuget package?
![captainpavextensionprob](https://cloud.githubusercontent.com/assets/6261719/8130514/f1542a62-10e0-11e5-8d54-9e1cddab1bd0.png)

**Comment by spelltwister** [comment]
Version 0.8 is a 3 dll solution.  Page modeling is in a different package and there is a third with the extensions.  Look at my nuget page for all the packages. 


     On Friday, June 12, 2015 8:56 AM, mkonkolowicz <notifications@github.com> wrote:
   

 PageModeling namespace not available in version 0.8 of extensions from nuget. I updated my solution and noticed that all my objects from the page modeling space are not being recognized. I then investigated on github and noticed that you updated the structure. Can you ensure the page modeling space is included in the nuget package?
