### ISSUE TITLE
No ChildPageModel For WPF? 

### ISSUE THREAD

**Issue by mkonkolowicz** [spelltwister/CodedUIFluentExtensions#6]
Mike, I was looking through the solution for page modelling (CaptainPav.Testing.UI.CodedUI.PageModelling) and noted that in the Html section, we're missing the HtmlChildPageModelBase. Is there a reason it was left out of the latest update?

M.

**Comment by spelltwister** [comment]
I remember leaving it out for a reason, but can't remember the reason so I've added it back in.  :D

**Comment by mkonkolowicz** [comment]
:)

On Saturday, 12 December 2015, Michael Pavlak <notifications@github.com>
wrote:

> I remember leaving it out for a reason, but can't remember the reason so
> I've added it back in. :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spelltwister/CodedUIFluentExtensions/issues/6#issuecomment-164175145>
> .
>


-- 
Cheers,
Maciek

**Comment by mkonkolowicz** [comment]
Also, I'd love to implement selenium components for cross browser
implementation. Do you think you could help me with that sometime in the
new year? I may have some questions and code reviews for you.

On Saturday, 12 December 2015, Maciej Konkolowicz <mkonkolowicz@gmail.com>
wrote:

> :)
>
> On Saturday, 12 December 2015, Michael Pavlak <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I remember leaving it out for a reason, but can't remember the reason so
>> I've added it back in. :D
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spelltwister/CodedUIFluentExtensions/issues/6#issuecomment-164175145>
>> .
>>
>
>
> --
> Cheers,
> Maciek
>
>

-- 
Cheers,
Maciek

**Comment by spelltwister** [comment]
We can talk about that more.  I'm working on cleaning up the project and getting a v 1.0 released.  I'd love to have you guys test it out for me :)

**Comment by mkonkolowicz** [comment]
Np. Let me know when it's ready. Will there be new features or just cleaned
up structure?

On Sunday, 13 December 2015, Michael Pavlak <notifications@github.com>
wrote:

> We can talk about that more. I'm working on cleaning up the project and
> getting a v 1.0 released. I'd love to have you guys test it out for me :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spelltwister/CodedUIFluentExtensions/issues/6#issuecomment-164286881>
> .
>


-- 
Cheers,
Maciek

**Comment by mkonkolowicz** [comment]
Hey,

One more question. I noticed as soon as I upgraded to VS 2015, coded ui
tests stopped working. Eventually I figured out that
CodedUIExtensionsAndHelpers v 0.7.9.0 requires v12.0 of
Microsoft.VisualStudio.TestTools.UITest.Extension. We didn't upgrade to the
later version of CodedUIExtensionsAndHelpers since WPFChild was missing.

What's your timeline on your new project re-structure being released? I'm
going to keep version 12.0 of UITest.Extension for now, but would like to
keep the MS references up to date, which means I need your DLL to reference
v14.0 of the tools.

Thoughts?

Cheers,
M.

On Sun, Dec 13, 2015 at 4:46 PM, Maciej Konkolowicz <mkonkolowicz@gmail.com>
wrote:

> Np. Let me know when it's ready. Will there be new features or just
> cleaned up structure?
>
>
> On Sunday, 13 December 2015, Michael Pavlak <notifications@github.com>
> wrote:
>
>> We can talk about that more. I'm working on cleaning up the project and
>> getting a v 1.0 released. I'd love to have you guys test it out for me :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spelltwister/CodedUIFluentExtensions/issues/6#issuecomment-164286881>
>> .
>>
>
>
> --
> Cheers,
> Maciek
>
>


-- 
Cheers,
Maciek

**Comment by spelltwister** [comment]
Mainly structure clean up.  Less inheritance, more composition.  I'll probably add in at least syntax from CUITe like

page.Find<HtmlDIv>(new { id = "myId" });

It'll definitely be breaking change.  Maybe we can get together sometime and I can try to apply the updates to an already modeled page to see how difficult the conversion is.  It'd help me a lot just having an app to test :)

**Comment by mkonkolowicz** [comment]
Sure. Perhaps the week after christmas? Where do you and Nick work on
things? I could make it out to one of those nights...

On Thu, Dec 17, 2015 at 5:30 PM, Michael Pavlak <notifications@github.com>
wrote:

> Mainly structure clean up. Less inheritance, more composition. I'll
> probably add in at least syntax from CUITe like
>
> page.Find(new { id = "myId" });
>
> It'll definitely be breaking change. Maybe we can get together sometime
> and I can try to apply the updates to an already modeled page to see how
> difficult the conversion is. It'd help me a lot just having an app to test
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spelltwister/CodedUIFluentExtensions/issues/6#issuecomment-165600666>
> .
>



-- 
Cheers,
Maciek

**Comment by mkonkolowicz** [comment]
Hey Mike,

Just join via this link: https://TitleSource.zoom.us/j/866704237

Next monday, 1030am.

See you then!

M.

On Thu, Dec 17, 2015 at 6:21 PM, Maciej Konkolowicz <mkonkolowicz@gmail.com>
wrote:

> Sure. Perhaps the week after christmas? Where do you and Nick work on
> things? I could make it out to one of those nights...
>
> On Thu, Dec 17, 2015 at 5:30 PM, Michael Pavlak <notifications@github.com>
> wrote:
>
>> Mainly structure clean up. Less inheritance, more composition. I'll
>> probably add in at least syntax from CUITe like
>>
>> page.Find(new { id = "myId" });
>>
>> It'll definitely be breaking change. Maybe we can get together sometime
>> and I can try to apply the updates to an already modeled page to see how
>> difficult the conversion is. It'd help me a lot just having an app to test
>> :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spelltwister/CodedUIFluentExtensions/issues/6#issuecomment-165600666>
>> .
>>
>
>
>
> --
> Cheers,
> Maciek
>



-- 
Cheers,
Maciek
