### ISSUE TITLE
Feature Request: Identifier For Logging on Elements

### ISSUE THREAD

**Issue by mkonkolowicz** [spelltwister/CodedUIFluentExtensions#9]
One of our top gunners was trying to iterate over a collection of items and wanted to incorporate a unique identifier (ie. name) of the element on which he would fail , in the assertion. Can you think of a way to do this? My only idea is to expose a unique identifier (automationid?) to the script, so we can use it to identify the element that throws the exception.

**Comment by spelltwister** [comment]
There are a few ways to do this.  If it's iterating over a combobox, there is INamedSelectionPageModel that gives a name for each thing inside the combobox.

Another way would be to create an extended page model which also implements a name.  eg,

interface IListIemPageModel<TNextModel> : INamedPageModel, IValuedPageModel<string> where TNextModel : IPageModel {
     
}

public class ListItemPageModel<TNextModel> : IListItemPageModel<TNextModel> {
    public string Name { get{return whateverNamePropertyYouWant; }}
}

public class ContainingControl : IPageModel {
    public IEnumerable<IListItemPageModel<IPageModel>> Items {get;}
}

public void TestMethod() {
    Assert.IsFalse(containingControl.Items.Any(x => x.Name == "Error"));
}

**Comment by mkonkolowicz** [comment]
Cool! Thanks Mike!

**Comment by spelltwister** [comment]
If you need something different, let me know.
